### ISSUE TITLE
wrong in splitSms?

### ISSUE THREAD

**Issue by programervn** [balamaci/sms-utils#1]
should change to  if (escapedContent.length() <= Encoding.GSM_7BIT.getMaxLengthSinglePart()) {
String escapedContent = escapeAny7BitExtendedCharsetInContent(content);
            if (content.length() <= Encoding.GSM_7BIT.getMaxLengthSinglePart()) {
                return new SmsParts(Encoding.GSM_7BIT, new String[] { escapedContent });
            } else {
                return new SmsParts(Encoding.GSM_7BIT, splitGsm7BitEncodedMessage(escapedContent));
            }

**Comment by balamaci** [comment]
You are right, 
Thanks!
